export default [
    {
        displayName: 'Blank',
        iconName: 'blank',
        tags: 'empty, placeholder',
        group: 'miscellaneous',
        content: '\\e900',
    },
    {
        displayName: 'Search around',
        iconName: 'search-around',
        tags: 'search, exploration, information, area, graph',
        group: 'action',
        content: '\\e608',
    },
    {
        displayName: 'Remove from graph',
        iconName: 'graph-remove',
        tags: 'circle, remove, delete, clear, graph',
        group: 'action',
        content: '\\e609',
    },
    {
        displayName: 'Group objects',
        iconName: 'group-objects',
        tags: 'group, alignment, organization, arrangement, classification, objects',
        group: 'action',
        content: '\\e60a',
    },
    {
        displayName: 'Geosearch',
        iconName: 'geosearch',
        tags: 'search, exploration, topography, geography, location, area, magnifying glass, globe',
        group: 'action',
        content: '\\e613',
    },
    {
        displayName: 'Heatmap',
        iconName: 'heatmap',
        tags: 'hierarchy, matrix, heat map',
        group: 'data',
        content: '\\e614',
    },
    {
        displayName: 'Drive time',
        iconName: 'drive-time',
        tags: 'car, automobile, vehicle, van, drive, ride, distance, navigation, directions',
        group: 'interface',
        content: '\\e615',
    },
    {
        displayName: 'Predictive analysis',
        iconName: 'predictive-analysis',
        tags: 'analysis, investigation, search, study, test, brain',
        group: 'action',
        content: '\\e617',
    },
    {
        displayName: 'Layers',
        iconName: 'layers',
        tags: 'layers, levels, stack, cards',
        group: 'interface',
        content: '\\e618',
    },
    {
        displayName: 'Locate',
        iconName: 'locate',
        tags: 'target, location, destination, mark, map, area',
        group: 'action',
        content: '\\e619',
    },
    {
        displayName: 'Bookmark',
        iconName: 'bookmark',
        tags: 'bookmark, marker, holder, section, identifier, favorites',
        group: 'action',
        content: '\\e61a',
    },
    {
        displayName: 'Tag',
        iconName: 'tag',
        tags: 'tag, label, badge, identification',
        group: 'action',
        content: '\\e61c',
    },
    {
        displayName: 'Clipboard',
        iconName: 'clipboard',
        tags: 'clipboard, notepad, notebook, copy, paste, transfer, storage',
        group: 'action',
        content: '\\e61d',
    },
    {
        displayName: 'Selection',
        iconName: 'selection',
        tags: 'selection, collection, circle, ring',
        group: 'action',
        content: '\\29bf',
    },
    {
        displayName: 'Events',
        iconName: 'timeline-events',
        tags: 'calendar, timeframe, agenda, diary, day, week, month',
        group: 'interface',
        content: '\\e61e',
    },
    {
        displayName: 'Line chart',
        iconName: 'timeline-line-chart',
        tags: 'graph, line, chart',
        group: 'data',
        content: '\\e61f',
    },
    {
        displayName: 'Bar chart',
        iconName: 'timeline-bar-chart',
        tags: 'graph, bar, chart',
        group: 'data',
        content: '\\e620',
    },
    {
        displayName: 'Applications',
        iconName: 'applications',
        tags: 'application, browser, windows, platforms',
        group: 'interface',
        content: '\\e621',
    },
    {
        displayName: 'Projects',
        iconName: 'projects',
        tags: 'drawer, sections',
        group: 'interface',
        content: '\\e622',
    },
    {
        displayName: 'Changes',
        iconName: 'changes',
        tags: 'arrows, direction, switch',
        group: 'action',
        content: '\\e623',
    },
    {
        displayName: 'Notifications',
        iconName: 'notifications',
        tags: 'notifications, bell, alarm, notice, warning',
        group: 'interface',
        content: '\\e624',
    },
    {
        displayName: 'Lock',
        iconName: 'lock',
        tags: 'lock, engage, connect, join, close',
        group: 'action',
        content: '\\e625',
    },
    {
        displayName: 'Unlock',
        iconName: 'unlock',
        tags: 'unlock, disengage, disconnect, separate, open',
        group: 'action',
        content: '\\e626',
    },
    {
        displayName: 'User',
        iconName: 'user',
        tags: 'person, human, male, female, character, customer, individual',
        group: 'interface',
        content: '\\e627',
    },
    {
        displayName: 'Search template',
        iconName: 'search-template',
        tags: 'search, text, magnifying glass',
        group: 'action',
        content: '\\e628',
    },
    {
        displayName: 'Inbox',
        iconName: 'inbox',
        tags: 'folder, mail, file, message',
        group: 'file',
        content: '\\e629',
    },
    {
        displayName: 'More',
        iconName: 'more',
        tags: 'dots, three, extra, new, options',
        group: 'interface',
        content: '\\e62a',
    },
    {
        displayName: 'Help',
        iconName: 'help',
        tags: 'question mark, aid, advice, circle',
        group: 'action',
        content: '\\003F',
    },
    {
        displayName: 'Calendar',
        iconName: 'calendar',
        tags: 'calendar, timeframe, agenda, diary, day, week, month',
        group: 'interface',
        content: '\\e62b',
    },
    {
        displayName: 'Media',
        iconName: 'media',
        tags: 'audio, video, media, picture, image, drawing, illustration',
        group: 'media',
        content: '\\e62c',
    },
    {
        displayName: 'Link',
        iconName: 'link',
        tags: 'link, connection, network',
        group: 'interface',
        content: '\\e62d',
    },
    {
        displayName: 'Share',
        iconName: 'share',
        tags: 'share, square, arrow',
        group: 'action',
        content: '\\e62e',
    },
    {
        displayName: 'Download',
        iconName: 'download',
        tags: 'circle, arrow, down, downloading',
        group: 'action',
        content: '\\e62f',
    },
    {
        displayName: 'Document',
        iconName: 'document',
        tags: 'document, paper, page, file',
        group: 'file',
        content: '\\e630',
    },
    {
        displayName: 'Properties',
        iconName: 'properties',
        tags: 'lines, dots, three, list',
        group: 'interface',
        content: '\\e631',
    },
    {
        displayName: 'Import',
        iconName: 'import',
        tags: 'arrow, down, importing,',
        group: 'action',
        content: '\\e632',
    },
    {
        displayName: 'Export',
        iconName: 'export',
        tags: 'arrow, up, exporting',
        group: 'action',
        content: '\\e633',
    },
    {
        displayName: 'Tick',
        iconName: 'tick',
        tags: 'mark, sign, ok, approved, success',
        group: 'action',
        content: '\\2713',
    },
    {
        displayName: 'Cross',
        iconName: 'cross',
        tags: 'cross mark, fail, delete, no, close, remove',
        group: 'action',
        content: '\\2717',
    },
    {
        displayName: 'Plus',
        iconName: 'plus',
        tags: 'sign, add, maximize, zoom in',
        group: 'action',
        content: '\\002b',
    },
    {
        displayName: 'Minus',
        iconName: 'minus',
        tags: 'sign, remove, minimize, zoom out',
        group: 'action',
        content: '\\2212',
    },
    {
        displayName: 'Comparison',
        iconName: 'comparison',
        tags: 'comparison, analogy, layout, contrast',
        group: 'action',
        content: '\\e637',
    },
    {
        displayName: 'Filter',
        iconName: 'filter',
        tags: 'filtering, funnel, tube, pipe',
        group: 'action',
        content: '\\e638',
    },
    {
        displayName: 'Confirm',
        iconName: 'confirm',
        tags: 'circle, tick, confirmation, acceptance, approval, authorization',
        group: 'action',
        content: '\\e639',
    },
    {
        displayName: 'Fork',
        iconName: 'fork',
        tags: 'divide, split, break, arrows, direction',
        group: 'action',
        content: '\\e63a',
    },
    {
        displayName: 'Trash',
        iconName: 'trash',
        tags: 'bin, rubbish, junk, remove, delete',
        group: 'action',
        content: '\\e63b',
    },
    {
        displayName: 'Person',
        iconName: 'person',
        tags: 'person, human, male, female, character, customer, individual',
        group: 'interface',
        content: '\\e63c',
    },
    {
        displayName: 'People',
        iconName: 'people',
        tags: 'people, humans, males, females, characters, customers, individuals',
        group: 'interface',
        content: '\\e63d',
    },
    {
        displayName: 'Add',
        iconName: 'add',
        tags: 'circle, plus, symbol, join',
        group: 'action',
        content: '\\e63e',
    },
    {
        displayName: 'Remove',
        iconName: 'remove',
        tags: 'circle, minus, symbol, remove',
        group: 'action',
        content: '\\e63f',
    },
    {
        displayName: 'Geolocation',
        iconName: 'geolocation',
        tags: 'geography, location, position, map, direction',
        group: 'interface',
        content: '\\e640',
    },
    {
        displayName: 'Refresh',
        iconName: 'refresh',
        tags: 'circle, arrows, rotation',
        group: 'action',
        content: '\\e643',
    },
    {
        displayName: 'Delete',
        iconName: 'delete',
        tags: 'circle, remove, cross',
        group: 'action',
        content: '\\e644',
    },
    {
        displayName: 'Cog',
        iconName: 'cog',
        tags: 'settings, circle,',
        group: 'interface',
        content: '\\e645',
    },
    {
        displayName: 'Flag',
        iconName: 'flag',
        tags: 'map, position, country, nationality',
        group: 'interface',
        content: '\\2691',
    },
    {
        displayName: 'Pin',
        iconName: 'pin',
        tags: 'map, position, safety pin, attach',
        group: 'action',
        content: '\\e646',
    },
    {
        displayName: 'Warning sign',
        iconName: 'warning-sign',
        tags: 'notification, warning, triangle, exclamation mark, sign',
        group: 'interface',
        content: '\\e647',
    },
    {
        displayName: 'Error',
        iconName: 'error',
        tags: 'notification, failure, circle, exclamation mark, sign',
        group: 'interface',
        content: '\\e648',
    },
    {
        displayName: 'Info sign',
        iconName: 'info-sign',
        tags: 'notification, information, circle, message, sign',
        group: 'interface',
        content: '\\2139',
    },
    {
        displayName: 'Credit card',
        iconName: 'credit-card',
        tags: 'payment, bank, transaction',
        group: 'action',
        content: '\\e649',
    },
    {
        displayName: 'Edit',
        iconName: 'edit',
        tags: 'annotate, pen, modify',
        group: 'action',
        content: '\\270E',
    },
    {
        displayName: 'History',
        iconName: 'history',
        tags: 'past, reverse, circle, arrow',
        group: 'action',
        content: '\\e64a',
    },
    {
        displayName: 'Search',
        iconName: 'search',
        tags: 'inspection, exploration, magnifying glass',
        group: 'action',
        content: '\\e64b',
    },
    {
        displayName: 'Logout',
        iconName: 'log-out',
        tags: 'arrow, leave',
        group: 'action',
        content: '\\e64c',
    },
    {
        displayName: 'Star',
        iconName: 'star',
        tags: 'shape, pin, mark, pro',
        group: 'interface',
        content: '\\2605',
    },
    {
        displayName: 'Star: empty',
        iconName: 'star-empty',
        tags: 'shape, unpin, mark',
        group: 'interface',
        content: '\\2606',
    },
    {
        displayName: 'Folder: opened',
        iconName: 'folder-open',
        tags: 'file, portfolio, case',
        group: 'file',
        content: '\\e651',
    },
    {
        displayName: 'Feed',
        iconName: 'feed',
        tags: 'rss, feed',
        group: 'interface',
        content: '\\e656',
    },
    {
        displayName: 'Two columns',
        iconName: 'two-columns',
        tags: 'layout, columns, switch, change, two',
        group: 'action',
        content: '\\e657',
    },
    {
        displayName: 'Dot',
        iconName: 'dot',
        tags: 'point, circle, small',
        group: 'miscellaneous',
        content: '\\2022',
    },
    {
        displayName: 'Property',
        iconName: 'property',
        tags: 'list, order',
        group: 'interface',
        content: '\\e65a',
    },
    {
        displayName: 'Time',
        iconName: 'time',
        tags: 'clock, day, hours, minutes, seconds',
        group: 'interface',
        content: '\\23F2',
    },
    {
        displayName: 'Disable',
        iconName: 'disable',
        tags: 'off, circle, remove',
        group: 'action',
        content: '\\e600',
    },
    {
        displayName: 'Unpin',
        iconName: 'unpin',
        tags: 'map, position, safety pin, detach',
        group: 'action',
        content: '\\e650',
    },
    {
        displayName: 'Flows',
        iconName: 'flows',
        tags: 'arrows, direction, links',
        group: 'data',
        content: '\\e659',
    },
    {
        displayName: 'New text box',
        iconName: 'new-text-box',
        tags: 'text box, edit, new, create',
        group: 'action',
        content: '\\e65b',
    },
    {
        displayName: 'New link',
        iconName: 'new-link',
        tags: 'create, add, plus, links',
        group: 'action',
        content: '\\e65c',
    },
    {
        displayName: 'New object',
        iconName: 'new-object',
        tags: 'create, add, plus, objects, circle',
        group: 'action',
        content: '\\e65d',
    },
    {
        displayName: 'Path search',
        iconName: 'path-search',
        tags: 'map, magnifying glass, position, location',
        group: 'action',
        content: '\\e65e',
    },
    {
        displayName: 'Automatic updates',
        iconName: 'automatic-updates',
        tags: 'circle, arrows, tick, amends, updates',
        group: 'action',
        content: '\\e65f',
    },
    {
        displayName: 'Code',
        iconName: 'code',
        tags: 'code, markup, language, tag',
        group: 'action',
        content: '\\e661',
    },
    {
        displayName: 'Map',
        iconName: 'map',
        tags: 'map, location, position, geography, world',
        group: 'interface',
        content: '\\e662',
    },
    {
        displayName: 'Search text',
        iconName: 'search-text',
        tags: 'magnifying glass, exploration',
        group: 'action',
        content: '\\e663',
    },
    {
        displayName: 'Envelope',
        iconName: 'envelope',
        tags: 'post, mail, send, email',
        group: 'interface',
        content: '\\2709',
    },
    {
        displayName: 'Paperclip',
        iconName: 'paperclip',
        tags: 'attachments, add',
        group: 'action',
        content: '\\e664',
    },
    {
        displayName: 'Label',
        iconName: 'label',
        tags: 'text, tag, ticket',
        group: 'interface',
        content: '\\e665',
    },
    {
        displayName: 'Globe',
        iconName: 'globe',
        tags: 'planet, earth, map, location, geography, world',
        group: 'miscellaneous',
        content: '\\e666',
    },
    {
        displayName: 'Home',
        iconName: 'home',
        tags: 'house, building, destination',
        group: 'miscellaneous',
        content: '\\2302',
    },
    {
        displayName: 'Radial',
        iconName: 'circle',
        tags: 'circle, empty, area, radius, selection',
        group: 'action',
        content: '\\e66a',
    },
    {
        displayName: 'Draw',
        iconName: 'draw',
        tags: 'selection, area, highlight, sketch',
        group: 'action',
        content: '\\e66b',
    },
    {
        displayName: 'Insert',
        iconName: 'insert',
        tags: 'square, plus, add, embed, include, inject',
        group: 'action',
        content: '\\e66c',
    },
    {
        displayName: 'Helper management',
        iconName: 'helper-management',
        tags: 'square, widget',
        group: 'interface',
        content: '\\e66d',
    },
    {
        displayName: 'Send to',
        iconName: 'send-to',
        tags: 'circle, export, arrow',
        group: 'action',
        content: '\\e66e',
    },
    {
        displayName: 'Eye',
        iconName: 'eye-open',
        tags: 'show, visible, clear, view, vision',
        group: 'interface',
        content: '\\e66f',
    },
    {
        displayName: 'Folder: shared open',
        iconName: 'folder-shared-open',
        tags: 'file, portfolio, case',
        group: 'file',
        content: '\\e670',
    },
    {
        displayName: 'Social media',
        iconName: 'social-media',
        tags: 'circle, rotate, share',
        group: 'action',
        content: '\\e671',
    },
    {
        displayName: 'Resolve',
        iconName: 'resolve',
        tags: 'circles, divide, split',
        group: 'action',
        content: '\\e672',
    },
    {
        displayName: 'Graph',
        iconName: 'graph',
        tags: 'graph, diagram',
        group: 'data',
        content: '\\e673',
    },
    {
        displayName: 'Briefcase',
        iconName: 'briefcase',
        tags: 'suitcase, business, case, baggage,',
        group: 'miscellaneous',
        content: '\\e674',
    },
    {
        displayName: 'Dollar',
        iconName: 'dollar',
        tags: 'currency, money',
        group: 'miscellaneous',
        content: '\\0024',
    },
    {
        displayName: 'Ninja',
        iconName: 'ninja',
        tags: 'star, fighter, symbol',
        group: 'miscellaneous',
        content: '\\e675',
    },
    {
        displayName: 'Delta',
        iconName: 'delta',
        tags: 'alt j, symbol',
        group: 'miscellaneous',
        content: '\\0394',
    },
    {
        displayName: 'Barcode',
        iconName: 'barcode',
        tags: 'product, scan,',
        group: 'miscellaneous',
        content: '\\e676',
    },
    {
        displayName: 'Torch',
        iconName: 'torch',
        tags: 'light, flashlight, tool',
        group: 'miscellaneous',
        content: '\\e677',
    },
    {
        displayName: 'Widget',
        iconName: 'widget',
        tags: 'square, corners',
        group: 'interface',
        content: '\\e678',
    },
    {
        displayName: 'Unresolve',
        iconName: 'unresolve',
        tags: 'split, divide, disconnect, separate',
        group: 'action',
        content: '\\e679',
    },
    {
        displayName: 'Offline',
        iconName: 'offline',
        tags: 'circle, lightning, disconnected, down',
        group: 'interface',
        content: '\\e67a',
    },
    {
        displayName: 'Zoom to fit',
        iconName: 'zoom-to-fit',
        tags: 'fit, scale, resize, adjust',
        group: 'action',
        content: '\\e67b',
    },
    {
        displayName: 'Add to artifact',
        iconName: 'add-to-artifact',
        tags: 'list, plus',
        group: 'action',
        content: '\\e67c',
    },
    {
        displayName: 'Map marker',
        iconName: 'map-marker',
        tags: 'pin, map, location, position, geography, world',
        group: 'interface',
        content: '\\e67d',
    },
    {
        displayName: 'Chart',
        iconName: 'chart',
        tags: 'arrow, increase, up, line, bar, graph',
        group: 'data',
        content: '\\e67e',
    },
    {
        displayName: 'Control',
        iconName: 'control',
        tags: 'squares, layout',
        group: 'interface',
        content: '\\e67f',
    },
    {
        displayName: 'Multi select',
        iconName: 'multi-select',
        tags: 'layers, selection',
        group: 'interface',
        content: '\\e680',
    },
    {
        displayName: 'Database',
        iconName: 'database',
        tags: 'stack, storage',
        group: 'data',
        content: '\\e683',
    },
    {
        displayName: 'Pie chart',
        iconName: 'pie-chart',
        tags: 'circle, part, section',
        group: 'data',
        content: '\\e684',
    },
    {
        displayName: 'Full circle',
        iconName: 'full-circle',
        tags: 'dot, point',
        group: 'miscellaneous',
        content: '\\e685',
    },
    {
        displayName: 'Square',
        iconName: 'square',
        tags: 'empty, outline',
        group: 'miscellaneous',
        content: '\\e686',
    },
    {
        displayName: 'Print',
        iconName: 'print',
        tags: 'printer, paper',
        group: 'action',
        content: '\\2399',
    },
    {
        displayName: 'Presentation',
        iconName: 'presentation',
        tags: 'display, presentation',
        group: 'interface',
        content: '\\e687',
    },
    {
        displayName: 'Ungroup objects',
        iconName: 'ungroup-objects',
        tags: 'split, divide, disconnect, separate',
        group: 'action',
        content: '\\e688',
    },
    {
        displayName: 'Chat',
        iconName: 'chat',
        tags: 'speech, conversation, communication, talk',
        group: 'action',
        content: '\\e689',
    },
    {
        displayName: 'Comment',
        iconName: 'comment',
        tags: 'statement, discussion, opinion, view',
        group: 'action',
        content: '\\e68a',
    },
    {
        displayName: 'Circle arrow: right',
        iconName: 'circle-arrow-right',
        tags: 'direction, east',
        group: 'interface',
        content: '\\e68b',
    },
    {
        displayName: 'Circle arrow: left',
        iconName: 'circle-arrow-left',
        tags: 'direction, west',
        group: 'interface',
        content: '\\e68c',
    },
    {
        displayName: 'Circle arrow: up',
        iconName: 'circle-arrow-up',
        tags: 'direction, north',
        group: 'interface',
        content: '\\e68d',
    },
    {
        displayName: 'Circle arrow: down',
        iconName: 'circle-arrow-down',
        tags: 'direction, south',
        group: 'interface',
        content: '\\e68e',
    },
    {
        displayName: 'Upload',
        iconName: 'upload',
        tags: 'arrow, circle, up, transfer',
        group: 'action',
        content: '\\e68f',
    },
    {
        displayName: 'Asterisk',
        iconName: 'asterisk',
        tags: 'note, symbol, starred, marked',
        group: 'miscellaneous',
        content: '\\002a',
    },
    {
        displayName: 'Cloud',
        iconName: 'cloud',
        tags: 'file, storage, weather',
        group: 'file',
        content: '\\2601',
    },
    {
        displayName: 'Cloud: download',
        iconName: 'cloud-download',
        tags: 'file, storage, transfer',
        group: 'file',
        content: '\\e690',
    },
    {
        displayName: 'Cloud: upload',
        iconName: 'cloud-upload',
        tags: 'file, storage, transfer',
        group: 'file',
        content: '\\e691',
    },
    {
        displayName: 'Repeat',
        iconName: 'repeat',
        tags: 'circle, arrow',
        group: 'action',
        content: '\\e692',
    },
    {
        displayName: 'Move',
        iconName: 'move',
        tags: 'arrows, directions, position, location',
        group: 'action',
        content: '\\e693',
    },
    {
        displayName: 'Random',
        iconName: 'random',
        tags: 'arrows, aim',
        group: 'interface',
        content: '\\e698',
    },
    {
        displayName: 'Fullscreen',
        iconName: 'fullscreen',
        tags: 'size, arrows, increase, proportion, width, height',
        group: 'media',
        content: '\\e699',
    },
    {
        displayName: 'Login',
        iconName: 'log-in',
        tags: 'arrow, sign in',
        group: 'action',
        content: '\\e69a',
    },
    {
        displayName: 'Heart',
        iconName: 'heart',
        tags: 'love, like, organ, human, feelings',
        group: 'miscellaneous',
        content: '\\2665',
    },
    {
        displayName: 'Office',
        iconName: 'office',
        tags: 'building, business, location, street',
        group: 'miscellaneous',
        content: '\\e69b',
    },
    {
        displayName: 'Duplicate',
        iconName: 'duplicate',
        tags: 'copy, square, two',
        group: 'action',
        content: '\\e69c',
    },
    {
        displayName: 'Ban circle',
        iconName: 'ban-circle',
        tags: 'circle, refusal',
        group: 'action',
        content: '\\e69d',
    },
    {
        displayName: 'Camera',
        iconName: 'camera',
        tags: 'photograph, picture, video',
        group: 'media',
        content: '\\e69e',
    },
    {
        displayName: 'Mobile video',
        iconName: 'mobile-video',
        tags: 'film, broadcast, television',
        group: 'media',
        content: '\\e69f',
    },
    {
        displayName: 'Video',
        iconName: 'video',
        tags: 'film, broadcast, television',
        group: 'media',
        content: '\\e6a0',
    },
    {
        displayName: 'Film',
        iconName: 'film',
        tags: 'movie, cinema, theatre',
        group: 'media',
        content: '\\e6a1',
    },
    {
        displayName: 'Settings',
        iconName: 'settings',
        tags: 'controls, knobs',
        group: 'media',
        content: '\\e6a2',
    },
    {
        displayName: 'Volume',
        iconName: 'volume-up',
        tags: 'audio, video, speaker, music, sound',
        group: 'media',
        content: '\\e6a5',
    },
    {
        displayName: 'Music',
        iconName: 'music',
        tags: 'audio, video, note, sound',
        group: 'media',
        content: '\\e6a6',
    },
    {
        displayName: 'Desktop',
        iconName: 'desktop',
        tags: 'screen, monitor, display',
        group: 'media',
        content: '\\e6af',
    },
    {
        displayName: 'Phone',
        iconName: 'phone',
        tags: 'telephone, call, ring',
        group: 'media',
        content: '\\260e',
    },
    {
        displayName: 'Lightbulb',
        iconName: 'lightbulb',
        tags: 'idea, glow, lamp',
        group: 'miscellaneous',
        content: '\\e6b0',
    },
    {
        displayName: 'Glass',
        iconName: 'glass',
        tags: 'glassware, drink',
        group: 'miscellaneous',
        content: '\\e6b1',
    },
    {
        displayName: 'Tint',
        iconName: 'tint',
        tags: 'drop, color, coloration, hue',
        group: 'media',
        content: '\\e6b2',
    },
    {
        displayName: 'Flash',
        iconName: 'flash',
        tags: 'light, contrast, photograph, picture',
        group: 'media',
        content: '\\e6b3',
    },
    {
        displayName: 'Saved',
        iconName: 'saved',
        tags: 'document, check mark, tick',
        group: 'file',
        content: '\\e6b6',
    },
    {
        displayName: 'Floppy disk',
        iconName: 'floppy-disk',
        tags: 'save',
        group: 'interface',
        content: '\\e6b7',
    },
    {
        displayName: 'Book',
        iconName: 'book',
        tags: 'pages, album, brochure, manual',
        group: 'miscellaneous',
        content: '\\e6b8',
    },
    {
        displayName: 'Hand: right',
        iconName: 'hand-right',
        tags: 'gesture, direction',
        group: 'interface',
        content: '\\e6b9',
    },
    {
        displayName: 'Hand: up',
        iconName: 'hand-up',
        tags: 'gesture, direction',
        group: 'interface',
        content: '\\e6ba',
    },
    {
        displayName: 'Hand: down',
        iconName: 'hand-down',
        tags: 'gesture, direction',
        group: 'interface',
        content: '\\e6bb',
    },
    {
        displayName: 'Hand: left',
        iconName: 'hand-left',
        tags: 'gesture, direction',
        group: 'interface',
        content: '\\e6bc',
    },
    {
        displayName: 'Thumbs: up',
        iconName: 'thumbs-up',
        tags: 'hand, like, ok',
        group: 'interface',
        content: '\\e6bd',
    },
    {
        displayName: 'Thumbs: down',
        iconName: 'thumbs-down',
        tags: 'hand, dislike, bad',
        group: 'interface',
        content: '\\e6be',
    },
    {
        displayName: 'Box',
        iconName: 'box',
        tags: 'folder, carton, pack',
        group: 'file',
        content: '\\e6bf',
    },
    {
        displayName: 'Compressed',
        iconName: 'compressed',
        tags: 'folder, carton, pack, shrink, wrap, shorten',
        group: 'file',
        content: '\\e6c0',
    },
    {
        displayName: 'Shopping cart',
        iconName: 'shopping-cart',
        tags: 'trolley, mall, online, store, business',
        group: 'miscellaneous',
        content: '\\e6c1',
    },
    {
        displayName: 'Shop',
        iconName: 'shop',
        tags: 'store, business, shopping',
        group: 'miscellaneous',
        content: '\\e6c2',
    },
    {
        displayName: 'Undo',
        iconName: 'undo',
        tags: 'back, cancel, reverse, revoke,',
        group: 'action',
        content: '\\238c',
    },
    {
        displayName: 'Redo',
        iconName: 'redo',
        tags: 'forward, push',
        group: 'action',
        content: '\\e6c4',
    },
    {
        displayName: 'Code block',
        iconName: 'code-block',
        tags: 'code, markup, language, tag',
        group: 'file',
        content: '\\e6c5',
    },
    {
        displayName: 'Take action',
        iconName: 'take-action',
        tags: 'case, court, deal, gavel',
        group: 'action',
        content: '\\e6ca',
    },
    {
        displayName: 'Contrast',
        iconName: 'contrast',
        tags: 'color, brightness',
        group: 'media',
        content: '\\e6cb',
    },
    {
        displayName: 'Eye: off',
        iconName: 'eye-off',
        tags: 'visibility, hide',
        group: 'interface',
        content: '\\e6cc',
    },
    {
        displayName: 'Area chart',
        iconName: 'timeline-area-chart',
        tags: 'graph, line, diagram',
        group: 'data',
        content: '\\e6cd',
    },
    {
        displayName: 'Doughnut chart',
        iconName: 'doughnut-chart',
        tags: 'circle, section, part, graph',
        group: 'data',
        content: '\\e6ce',
    },
    {
        displayName: 'Layer',
        iconName: 'layer',
        tags: 'zone, level',
        group: 'interface',
        content: '\\e6cf',
    },
    {
        displayName: 'Grid',
        iconName: 'grid',
        tags: 'layout, arrangement',
        group: 'data',
        content: '\\e6d0',
    },
    {
        displayName: 'Polygon filter',
        iconName: 'polygon-filter',
        tags: 'shape, form',
        group: 'data',
        content: '\\e6d1',
    },
    {
        displayName: 'Add to folder',
        iconName: 'add-to-folder',
        tags: 'file, portfolio, case, import',
        group: 'file',
        content: '\\e6d2',
    },
    {
        displayName: 'Layout: balloon',
        iconName: 'layout-balloon',
        tags: 'layout, presentation, arrangement, graph',
        group: 'data',
        content: '\\e6d3',
    },
    {
        displayName: 'Layout: sorted clusters',
        iconName: 'layout-sorted-clusters',
        tags: 'layout, presentation, arrangement, graph',
        group: 'data',
        content: '\\e6d4',
    },
    {
        displayName: 'Small cross',
        iconName: 'small-cross',
        tags: 'cross mark, fail, delete, no, close, remove',
        group: 'action',
        content: '\\e6d7',
    },
    {
        displayName: 'Small tick',
        iconName: 'small-tick',
        tags: 'mark, sign, ok, approved, success',
        group: 'action',
        content: '\\e6d8',
    },
    {
        displayName: 'Power',
        iconName: 'power',
        tags: 'button, on, off',
        group: 'media',
        content: '\\e6d9',
    },
    {
        displayName: 'Mugshot',
        iconName: 'mugshot',
        tags: 'person, photograph, picture,',
        group: 'interface',
        content: '\\e6db',
    },
    {
        displayName: 'Headset',
        iconName: 'headset',
        tags: 'headphones, call, communication',
        group: 'media',
        content: '\\e6dc',
    },
    {
        displayName: 'Hand',
        iconName: 'hand',
        tags: 'gesture, fingers',
        group: 'interface',
        content: '\\e6de',
    },
    {
        displayName: 'Badge',
        iconName: 'badge',
        tags: 'emblem, symbol, identification, insignia, marker',
        group: 'miscellaneous',
        content: '\\e6e3',
    },
    {
        displayName: 'Pulse',
        iconName: 'pulse',
        tags: 'medical, life, heartbeat, hospital',
        group: 'miscellaneous',
        content: '\\e6e8',
    },
    {
        displayName: 'New person',
        iconName: 'new-person',
        tags: 'person, human, male, female, character, customer, individual, add',
        group: 'interface',
        content: '\\e6e9',
    },
    {
        displayName: 'Segmented control',
        iconName: 'segmented-control',
        tags: 'button, switch, option',
        group: 'interface',
        content: '\\e6ec',
    },
    {
        displayName: 'Highlight',
        iconName: 'highlight',
        tags: 'select, text',
        group: 'action',
        content: '\\e6ed',
    },
    {
        displayName: 'Filter: list',
        iconName: 'filter-list',
        tags: 'filtering, funnel, tube, pipe',
        group: 'action',
        content: '\\e6ee',
    },
    {
        displayName: 'Cut',
        iconName: 'cut',
        tags: 'scissors',
        group: 'action',
        content: '\\e6ef',
    },
    {
        displayName: 'Pivot',
        iconName: 'pivot',
        tags: 'rotate, axis',
        group: 'action',
        content: '\\e6f1',
    },
    {
        displayName: 'Ring',
        iconName: 'ring',
        tags: 'empty, circle, selection',
        group: 'miscellaneous',
        content: '\\e6f2',
    },
    {
        displayName: 'Heat grid',
        iconName: 'heat-grid',
        tags: 'chart',
        group: 'data',
        content: '\\e6f3',
    },
    {
        displayName: 'Manual',
        iconName: 'manual',
        tags: 'guide, instruction',
        group: 'interface',
        content: '\\e6f6',
    },
    {
        displayName: 'Key: control',
        iconName: 'key-control',
        tags: 'interface, shortcuts, buttons',
        group: 'media',
        content: '\\e704',
    },
    {
        displayName: 'Key: command',
        iconName: 'key-command',
        tags: 'interface, shortcuts, buttons',
        group: 'media',
        content: '\\e705',
    },
    {
        displayName: 'Key: shift',
        iconName: 'key-shift',
        tags: 'interface, shortcuts, buttons',
        group: 'media',
        content: '\\e706',
    },
    {
        displayName: 'Key: backspace',
        iconName: 'key-backspace',
        tags: 'interface, shortcuts, buttons',
        group: 'media',
        content: '\\e707',
    },
    {
        displayName: 'Key: delete',
        iconName: 'key-delete',
        tags: 'interface, shortcuts, buttons',
        group: 'media',
        content: '\\e708',
    },
    {
        displayName: 'Key: escape',
        iconName: 'key-escape',
        tags: 'interface, shortcuts, buttons',
        group: 'media',
        content: '\\e709',
    },
    {
        displayName: 'Key: enter',
        iconName: 'key-enter',
        tags: 'interface, shortcuts, buttons',
        group: 'media',
        content: '\\e70a',
    },
    {
        displayName: 'Calculator',
        iconName: 'calculator',
        tags: 'math, device, value, numbers, total',
        group: 'miscellaneous',
        content: '\\e70b',
    },
    {
        displayName: 'Small plus',
        iconName: 'small-plus',
        tags: 'sign, add, maximize, zoom in',
        group: 'action',
        content: '\\e70d',
    },
    {
        displayName: 'Small minus',
        iconName: 'small-minus',
        tags: 'sign, remove, minimize, zoom out',
        group: 'action',
        content: '\\e70e',
    },
    {
        displayName: 'Euro',
        iconName: 'euro',
        tags: 'currency, money',
        group: 'miscellaneous',
        content: '\\20ac',
    },
    {
        displayName: 'Mobile phone',
        iconName: 'mobile-phone',
        tags: 'cellular, device, call',
        group: 'media',
        content: '\\e717',
    },
    {
        displayName: 'Sim card',
        iconName: 'sim-card',
        tags: 'phone, cellular',
        group: 'media',
        content: '\\e718',
    },
    {
        displayName: 'Trending: up',
        iconName: 'trending-up',
        tags: 'growth, incline, progress',
        group: 'data',
        content: '\\e719',
    },
    {
        displayName: 'Trending: down',
        iconName: 'trending-down',
        tags: 'decrease, decline, loss',
        group: 'data',
        content: '\\e71a',
    },
    {
        displayName: 'Document: open',
        iconName: 'document-open',
        tags: 'paper, access',
        group: 'file',
        content: '\\e71e',
    },
    {
        displayName: 'Document: share',
        iconName: 'document-share',
        tags: 'paper, send',
        group: 'file',
        content: '\\e71f',
    },
    {
        displayName: 'Git: pull',
        iconName: 'git-pull',
        tags: 'github, repository, code, command',
        group: 'action',
        content: '\\e728',
    },
    {
        displayName: 'Git: branch',
        iconName: 'git-branch',
        tags: 'github, repository, code, command',
        group: 'action',
        content: '\\e72a',
    },
    {
        displayName: 'Git: commit',
        iconName: 'git-commit',
        tags: 'github, repository, code, command',
        group: 'action',
        content: '\\e72b',
    },
    {
        displayName: 'Git: push',
        iconName: 'git-push',
        tags: 'github, repository, code, command',
        group: 'action',
        content: '\\e72c',
    },
    {
        displayName: 'Build',
        iconName: 'build',
        tags: 'hammer, tool',
        group: 'action',
        content: '\\e72d',
    },
    {
        displayName: 'Symbol: circle',
        iconName: 'symbol-circle',
        tags: 'shape, figure',
        group: 'interface',
        content: '\\e72e',
    },
    {
        displayName: 'Symbol: square',
        iconName: 'symbol-square',
        tags: 'shape, figure',
        group: 'interface',
        content: '\\e72f',
    },
    {
        displayName: 'Symbol: diamond',
        iconName: 'symbol-diamond',
        tags: 'shape, figure',
        group: 'interface',
        content: '\\e730',
    },
    {
        displayName: 'Symbol: cross',
        iconName: 'symbol-cross',
        tags: 'shape, figure',
        group: 'interface',
        content: '\\e731',
    },
    {
        displayName: 'Symbol: triangle up',
        iconName: 'symbol-triangle-up',
        tags: 'shape, figure',
        group: 'interface',
        content: '\\e732',
    },
    {
        displayName: 'Symbol: triangle down',
        iconName: 'symbol-triangle-down',
        tags: 'shape, figure',
        group: 'interface',
        content: '\\e733',
    },
    {
        displayName: 'Wrench',
        iconName: 'wrench',
        tags: 'tool, repair',
        group: 'miscellaneous',
        content: '\\e734',
    },
    {
        displayName: 'Application',
        iconName: 'application',
        tags: 'application, browser, windows, platform',
        group: 'interface',
        content: '\\e735',
    },
    {
        displayName: 'Send to graph',
        iconName: 'send-to-graph',
        tags: 'transfer, move',
        group: 'action',
        content: '\\e736',
    },
    {
        displayName: 'Send to map',
        iconName: 'send-to-map',
        tags: 'transfer, move',
        group: 'action',
        content: '\\e737',
    },
    {
        displayName: 'Derive column',
        iconName: 'derive-column',
        tags: 'table, obtain, get, take, develop',
        group: 'action',
        content: '\\e739',
    },
    {
        displayName: 'Rotate image: left',
        iconName: 'image-rotate-left',
        tags: 'picture, turn, alternate',
        group: 'media',
        content: '\\e73a',
    },
    {
        displayName: 'Rotate image: right',
        iconName: 'image-rotate-right',
        tags: 'picture, turn, alternate',
        group: 'media',
        content: '\\e73b',
    },
    {
        displayName: 'Known vehicle',
        iconName: 'known-vehicle',
        tags: 'car, automobile, vehicle, van, drive, ride, distance, navigation, directions',
        group: 'interface',
        content: '\\e73c',
    },
    {
        displayName: 'Unknown vehicle',
        iconName: 'unknown-vehicle',
        tags: 'car, automobile, vehicle, van, drive, ride, distance, navigation, directions',
        group: 'interface',
        content: '\\e73d',
    },
    {
        displayName: 'Scatter plot',
        iconName: 'scatter-plot',
        tags: 'graph, diagram',
        group: 'data',
        content: '\\e73e',
    },
    {
        displayName: 'Oil field',
        iconName: 'oil-field',
        tags: 'fuel, petroleum, gas, well, drilling, pump',
        group: 'interface',
        content: '\\e73f',
    },
    {
        displayName: 'Rig',
        iconName: 'rig',
        tags: 'fuel, petroleum, gas, well, drilling',
        group: 'interface',
        content: '\\e740',
    },
    {
        displayName: 'New map',
        iconName: 'map-create',
        tags: 'map, location, position, geography, world',
        group: 'interface',
        content: '\\e741',
    },
    {
        displayName: 'Key: option',
        iconName: 'key-option',
        tags: 'interface, shortcuts, buttons',
        group: 'media',
        content: '\\e742',
    },
    {
        displayName: 'Swap: vertical',
        iconName: 'swap-vertical',
        tags: 'direction, position, opposite, inverse',
        group: 'interface',
        content: '\\e744',
    },
    {
        displayName: 'Swap: horizontal',
        iconName: 'swap-horizontal',
        tags: 'direction, position, opposite, inverse',
        group: 'interface',
        content: '\\e745',
    },
    {
        displayName: 'Numbered list',
        iconName: 'numbered-list',
        tags: 'order, list, array, arrange',
        group: 'action',
        content: '\\e746',
    },
    {
        displayName: 'Git: repo',
        iconName: 'git-repo',
        tags: 'github, repository, code, command',
        group: 'action',
        content: '\\e748',
    },
    {
        displayName: 'Airplane',
        iconName: 'airplane',
        tags: 'flight, jet, travel, trip, transport, take-off',
        group: 'interface',
        content: '\\e74b',
    },
    {
        displayName: 'Dashboard',
        iconName: 'dashboard',
        tags: 'panel, control, gauge, instrument, meter',
        group: 'interface',
        content: '\\e751',
    },
    {
        displayName: 'Path',
        iconName: 'path',
        tags: 'hierarchy, trail, steps',
        group: 'interface',
        content: '\\e753',
    },
    {
        displayName: 'Moon',
        iconName: 'moon',
        tags: 'night, sky, dark',
        group: 'miscellaneous',
        content: '\\e754',
    },
    {
        displayName: 'Numerical',
        iconName: 'numerical',
        tags: 'numbers, order, sort, arrange, array',
        group: 'action',
        content: '\\e756',
    },
    {
        displayName: 'Key: tab',
        iconName: 'key-tab',
        tags: 'interface, shortcuts, buttons',
        group: 'media',
        content: '\\e757',
    },
    {
        displayName: 'Regression chart',
        iconName: 'regression-chart',
        tags: 'graph, line, chart',
        group: 'data',
        content: '\\e758',
    },
    {
        displayName: 'Translate',
        iconName: 'translate',
        tags: 'language, convert',
        group: 'action',
        content: '\\e759',
    },
    {
        displayName: 'Eye: on',
        iconName: 'eye-on',
        tags: 'visibility, show',
        group: 'interface',
        content: '\\e75a',
    },
    {
        displayName: 'Endorsed',
        iconName: 'endorsed',
        tags: 'tick, mark, sign, ok, approved, success',
        group: 'action',
        content: '\\e75f',
    },
    {
        displayName: 'Follower',
        iconName: 'follower',
        tags: 'person, human, male, female, character, customer, individual, social',
        group: 'interface',
        content: '\\e760',
    },
    {
        displayName: 'Following',
        iconName: 'following',
        tags: 'person, human, male, female, character, customer, individual, social',
        group: 'interface',
        content: '\\e761',
    },
    {
        displayName: 'Menu',
        iconName: 'menu',
        tags: 'navigation, lines, list',
        group: 'interface',
        content: '\\e762',
    },
    {
        displayName: 'Intersection',
        iconName: 'intersection',
        tags: 'circles, combine, cross',
        group: 'action',
        content: '\\e765',
    },
    {
        displayName: 'Blocked person',
        iconName: 'blocked-person',
        tags: 'person, human, male, female, character, customer, individual, social, banned, prohibited',
        group: 'interface',
        content: '\\e768',
    },
    {
        displayName: 'Slash',
        iconName: 'slash',
        tags: 'divide, separate',
        group: 'action',
        content: '\\e769',
    },
    {
        displayName: 'Percentage',
        iconName: 'percentage',
        tags: 'modulo, modulus',
        group: 'action',
        content: '\\e76a',
    },
    {
        displayName: 'Satellite',
        iconName: 'satellite',
        tags: 'communication, space',
        group: 'miscellaneous',
        content: '\\e76b',
    },
    {
        displayName: 'Bank account',
        iconName: 'bank-account',
        tags: 'money, finance, funds',
        group: 'miscellaneous',
        content: '\\e76f',
    },
    {
        displayName: 'Cell tower',
        iconName: 'cell-tower',
        tags: 'signal, communication, radio, mast',
        group: 'miscellaneous',
        content: '\\e770',
    },
    {
        displayName: 'ID number',
        iconName: 'id-number',
        tags: 'identification, person, document',
        group: 'miscellaneous',
        content: '\\e771',
    },
    {
        displayName: 'IP address',
        iconName: 'ip-address',
        tags: 'internet, protocol, number, id, network',
        group: 'miscellaneous',
        content: '\\e772',
    },
    {
        displayName: 'Issue',
        iconName: 'issue',
        tags: 'circle, notification, failure, circle, exclamation mark, sign, problem',
        group: 'interface',
        content: '\\e774',
    },
    {
        displayName: 'Issue: new',
        iconName: 'issue-new',
        tags: 'circle, notification, failure, circle, exclamation mark, sign, problem',
        group: 'interface',
        content: '\\e775',
    },
    {
        displayName: 'Issue: closed',
        iconName: 'issue-closed',
        tags: 'circle, notification, failure, circle, exclamation mark, sign, problem',
        group: 'interface',
        content: '\\e776',
    },
    {
        displayName: 'Tick circle',
        iconName: 'tick-circle',
        tags: 'mark, sign, ok, approved, success',
        group: 'action',
        content: '\\e779',
    },
    {
        displayName: 'Prescription',
        iconName: 'prescription',
        tags: 'instruction, direction, medicine, drug, medication, mixture',
        group: 'miscellaneous',
        content: '\\e78a',
    },
    {
        displayName: 'Prescription: new',
        iconName: 'new-prescription',
        tags: 'instruction, direction, medicine, drug, medication, mixture',
        group: 'miscellaneous',
        content: '\\e78b',
    },
    {
        displayName: 'Filter: keep',
        iconName: 'filter-keep',
        tags: 'filtering, funnel, tube, pipe, retain, stay',
        group: 'action',
        content: '\\e78c',
    },
    {
        displayName: 'Filter: remove',
        iconName: 'filter-remove',
        tags: 'filtering, funnel, tube, pipe, delete, detach, discard, dismiss',
        group: 'action',
        content: '\\e78d',
    },
    {
        displayName: 'Key',
        iconName: 'key',
        tags: 'lock, unlock, open, security, password, access',
        group: 'interface',
        content: '\\e78e',
    },
    {
        displayName: 'Feed: subscribed',
        iconName: 'feed-subscribed',
        tags: 'rss, feed, tick, check',
        group: 'interface',
        content: '\\e78f',
    },
    {
        displayName: 'Widget: button',
        iconName: 'widget-button',
        tags: 'element, click, press',
        group: 'interface',
        content: '\\e790',
    },
    {
        displayName: 'Widget: header',
        iconName: 'widget-header',
        tags: 'element, layout, top',
        group: 'interface',
        content: '\\e791',
    },
    {
        displayName: 'Widget: footer',
        iconName: 'widget-footer',
        tags: 'element, layout, bottom',
        group: 'interface',
        content: '\\e792',
    },
    {
        displayName: 'Form',
        iconName: 'form',
        tags: 'response, fill',
        group: 'data',
        content: '\\e795',
    },
    {
        displayName: 'Console',
        iconName: 'console',
        tags: 'terminal, coding',
        group: 'interface',
        content: '\\e79b',
    },
    {
        displayName: 'Compass',
        iconName: 'compass',
        tags: 'map, direction',
        group: 'interface',
        content: '\\e79c',
    },
    {
        displayName: 'Walk',
        iconName: 'walk',
        tags: 'transportation, run, move',
        group: 'interface',
        content: '\\e79d',
    },
    {
        displayName: 'Taxi',
        iconName: 'taxi',
        tags: 'transportation, car, move',
        group: 'interface',
        content: '\\e79e',
    },
    {
        displayName: 'Train',
        iconName: 'train',
        tags: 'transportation, public, move',
        group: 'interface',
        content: '\\e79f',
    },
    {
        displayName: 'Heart: broken',
        iconName: 'heart-broken',
        tags: 'love, like, organ, human, feelings, split, torn, failed, health',
        group: 'miscellaneous',
        content: '\\e7a2',
    },
    {
        displayName: 'Join',
        iconName: 'left-join',
        tags: 'circles, combine, connect, add, part, slice',
        group: 'action',
        content: '\\e7a4',
    },
    {
        displayName: 'Updated',
        iconName: 'updated',
        tags: 'time, recent, success',
        group: 'interface',
        content: '\\e7a7',
    },
    {
        displayName: 'Outdated',
        iconName: 'outdated',
        tags: 'time, error, warning',
        group: 'interface',
        content: '\\e7a8',
    },
    {
        displayName: 'Flame',
        iconName: 'flame',
        tags: 'fire, trendy, hot, popular',
        group: 'miscellaneous',
        content: '\\e7a9',
    },
    {
        displayName: 'Folder: new',
        iconName: 'folder-new',
        tags: 'create, group, organize, sort',
        group: 'file',
        content: '\\e7b0',
    },
    {
        displayName: 'Mountain',
        iconName: 'mountain',
        tags: 'summit, climb, peak',
        group: 'miscellaneous',
        content: '\\e7b1',
    },
    {
        displayName: 'Shield',
        iconName: 'shield',
        tags: 'protect, protection, secure, security, safe, safety, privacy, marking, control',
        group: 'miscellaneous',
        content: '\\e7b2',
    },
];
